### ISSUE TITLE
loading tex code from Google Docs requires double-clicking twice

### ISSUE THREAD

**Issue by npjg** [mathaddons/tex-math-here#4]
It seems that the first double-click on a TeX Math Here image selects the image in Docs, and then the second click is actually passed to the double-click listener. Has Google Docs changed this functionality on their end, just as they seem to be caching inserted images and not reloading them from the URL each time?

**Comment by DavidSchweitzer** [comment]
This was somewhat intentional, or at least the only workaround to the problem we were trying to address.

Interacting with existing TMH creations is highly platform dependent, to the point where that development was abandoned.  Each platform had a different way of interacting with images, resulting in idiosyncrasies such as the double double click for Google or even a complete inability to edit via clicking (MS Office Online...consistent with behavior seen by IguanaTeX in the desktop version and likely due to some form of security concern).   This required individualized coding contrary to TMH's approach.  Therefore, it never went further than the experimental stage, though it does work in Google Docs.
